name: Build and Test

on:
  push:
    branches:
      - main

jobs:

  exams_db:
    runs-on: ubuntu-latest
    
    outputs:
      steps_completed: ${{ steps.completed }}
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install mimesis
        pip install faker
        pip install flask

    - name: Build DB
      run: python ./db/func_db.py

  young_old_student:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        amount_student: [8,10,12,14,16,18,20,24,28,31]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install requests

    - name: Build App
      run: python ./app/task.py ${{ matrix.amount_student }}

  deploy_flask:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        amount_student: [8,10,12,14,16,18,20,24,28,31]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install requests
        pip install mimesis
        pip install faker
        pip install flask

    - name: Build App
      run: |
        python ./db/func_db.py
        python ./app/task.py ${{ matrix.amount_student }}