name: Build and Test

on:
  push:
    branches:
      - main

jobs:

  exams_db:
    runs-on: ubuntu-latest
    
    outputs:
      steps_completed: ${{ steps.completed }}
    
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        dockerfile: db/Dockerfile
        context: .

    - name: Install dependencies
      run: |
        pip install mimesis
        pip install faker
        pip install flask


    - name: Build DB
      run: docker build -t func_db .

  young_old_student:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        amount_student: [8,10,12,14,16,18,20,24,28,31]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Docker
      uses: docker/setup-docker@v2
      with:
        dockerfile: app/Dockerfile 
        context: .

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install requests
    
     - name: Build and run Docker containers
      run: |
        docker-compose build
        docker-compose up -d

     - name: Build AppRun task.py with argument
      run: docker exec -it $(docker-compose ps -q task_app) python task.py ${{ matrix.amount_student }}