name: Build and Test

on:
  push:
    branches:
      - main

jobs:

  exams_db:
    runs-on: ubuntu-latest
    
    outputs:
      steps_completed: ${{ steps.completed }}
    
    steps:

    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Build and run Docker containers
      run: |
        docker-compose build
        docker-compose up -d

    - name: Build DB
      run: docker exec -it $(docker-compose ps -q db_app) python func_db.py

  young_old_student:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        amount_student: [8,10,12,14,16,18,20,24,28,31]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2


    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x
    
     - name: Build and run Docker containers
      run: |
        docker-compose build
        docker-compose up -d

     - name: Build App
      run: docker exec -it $(docker-compose ps -q task_app) python task.py ${{ matrix.amount_student }}