name: Build and Test

on:
  push:
    branches:
      - main

jobs:

  exams_db:
    runs-on: ubuntu-latest
    
    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        pip install mimesis
        pip install faker
        pip install flask

    - name: Build DB
      run: python create_and_edit_db.py

  young_old_student:
    needs: exams_db
    runs-on: ubuntu-latest

    strategy:
      matrix:
        amount_student: [32]

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Build App
      run: python ./app/task.py ${{ matrix.amount_student }}