name: Build and Test

on:
  push:
    branches:
      - main

jobs:

  test_db:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        amount_student: [32]
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Test DB
      run: |
        python ./db/create_and_edit_db.py ${{ matrix.amount_student }}
    
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Build and Test App
      run: |
        python ./app/task.py 
